PH\Component\Subscription\Model\Subscription:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
            groups: [Default, Detailed]
        amount:
            expose: true
            type: integer
            groups: [Default, Detailed]
        currencyCode:
            expose: true
            type: string
            groups: [Default, Detailed]
        interval:
            expose: true
            type: string
            groups: [Default, Detailed]
        type:
            expose: true
            type: string
            groups: [Default, Detailed]
        startDate:
            expose: true
            type: DateTime
            groups: [Default, Detailed]
        items:
            expose: true
            type: array
            groups: [Default, Detailed]
        itemsTotal:
            expose: true
            type: integer
            groups: [Default, Detailed]
        total:
            expose: true
            type: integer
            groups: [Default, Detailed]
        state:
            expose: true
            type: string
            groups: [Detailed]
        purchaseCompletedAt:
            expose: true
            groups: [Detailed]
        createdAt:
            expose: true
            type: DateTime
            groups: [Detailed]
        updatedAt:
            expose: true
            type: DateTime
            groups: [Detailed]
