services:
    ph.form.type.subscription:
        class: PH\Bundle\SubscriptionBundle\Form\Type\SubscriptionType
        arguments:
            - '%ph.model.subscription.class%'
            - ['ph']
        tags:
            - { name: form.type }

    ph.form.type.start_date_choice:
        class: PH\Bundle\SubscriptionBundle\Form\Type\StartDateChoiceType
        arguments:
            - '@ph.provider.start_date'
        tags:
            - { name: form.type }

    ph.form.type.interval_choice:
        class: PH\Bundle\SubscriptionBundle\Form\Type\IntervalChoiceType
        arguments:
            - '@ph.provider.subscription_intervals'
        tags:
            - { name: form.type }
