PH\Component\Core\Model\Order:
    exclusion_policy: ALL
    xml_root_name: order
    properties:
        payments:
            expose: true
            type: array
            groups: [Default, Detailed]
    relations:
        -   rel: self
            href:
                route: sylius_api_order_show
                parameters:
                    id: expr(object.getId())
                    version: 1
