PH\Component\Core\Model\PaymentMethod:
    exclusion_policy: ALL
    properties:
        gatewayConfig:
            expose: true
        supportsRecurring:
            type: boolean
            expose: true
    relations:
        -   rel: self
            href:
                route: sylius_api_payment_method_show
                parameters:
                    code: expr(object.getCode())
                    version: 1
