parameters:
    payum.template.sepa_obtain_bank_details: '@@PHPayum/Action/obtain_sepa_bank_account.html.twig'

services:
    # generic
    ph.payum_action.capture_payment:
        class: PH\Bundle\PayumBundle\Action\CapturePaymentAction
        arguments:
            - '@ph.payum.provider.payment_description'
        tags:
            - { name: "payum.action", all: true, alias: "sylius.capture_payment"}

    ph.payum_action.resolve_next_url:
        class: PH\Bundle\PayumBundle\Action\ResolveNextUrlAction
        arguments:
            - '%ph.payum.redirect.thank_you_url%'
            - '%ph.payum.redirect.cancel_url%'
        tags:
            - { name: "payum.action", all: true, alias: "ph.resolve_next_url"}

    ph.payum_action.obtain_bank_account:
        class: PH\Bundle\PayumBundle\Action\ObtainBankAccountAction
        arguments:
            - '@ph.form.factory.bank_account'
            - '%payum.template.sepa_obtain_bank_details%'
        calls:
            - method: setRequestStack
              arguments:
                  - '@request_stack'
        tags:
            - { name: "payum.action", all: true, alias: "ph.obtain_bank_account"}

    # Paypal
    ph.payum_action.paypal_express_checkout.convert_payment:
        class: PH\Bundle\PayumBundle\Action\Paypal\ExpressCheckout\ConvertPaymentAction
        arguments:
            - '@ph.payum.provider.payment_description'
        tags:
            - { name: "payum.action", factory: "paypal_express_checkout", alias: "sylius.paypal_express_checkout.convert_payment"}

    # Mollie
    ph.payum_action.mollie.obtain_sepa_bank_account:
        class: PH\Bundle\PayumBundle\Action\Mollie\SepaDirectDebit\ObtainBankAccountAction
        tags:
            - { name: "payum.action", factory: "mollie", alias: "ph.mollie.obtain_sepa_bank_account"}

    ph.payum_action.mollie.obtain_sepa_one_off_bank_account:
        class: PH\Bundle\PayumBundle\Action\Mollie\SepaDirectDebit\SepaOneOffObtainBankAccountAction
        tags:
            - { name: "payum.action", factory: "mollie", alias: "ph.mollie.obtain_sepa_one_off_bank_account"}

    # Offline
    ph.payum_action.offline.resolve_next_url:
        class: PH\Bundle\PayumBundle\Action\Offline\ResolveNextUrlAction
        arguments:
            - '%ph.payum.redirect.thank_you_url%'
        tags:
            - { name: "payum.action", factory: "offline", alias: "ph.offline.resolve_next_url"}