services:
    ph.controller.payum:
      alias: sylius.controller.payum

    sylius.controller.payum:
      class: PH\Bundle\PayumBundle\Controller\PayumController
      arguments:
          - '@payum'
          - '@ph.repository.subscription'
          - "@=service('sylius.resource_registry').get('ph.subscription')"
          - '@sylius.resource_controller.request_configuration_factory'
          - '@sylius.resource_controller.view_handler'
          - '@router'
          - '@sylius.repository.payment'
          - '@ph.payum.factory.resolve_next_url'

    ph.payum.mollie.factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Sourcefabric\Payum\Mollie\MollieGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: mollie }

    ph.payum.mbe4.factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Sourcefabric\Payum\Mbe4\Mbe4GatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: mbe4 }

    ph.payum.factory.resolve_next_url:
        class: PH\Bundle\PayumBundle\Factory\ResolveNextUrlFactory

    ph.payum.provider.payment_description:
        class: PH\Bundle\PayumBundle\Provider\PaymentDescriptionProvider
        arguments:
            - '@translator'
