services:
    ph.controller.payum:
      class: PH\Bundle\PayumBundle\Controller\PayumController
      arguments:
          - '@payum'
          - '@sylius.repository.order'
          - "@=service('sylius.resource_registry').get('sylius.order')"
          - '@sylius.resource_controller.request_configuration_factory'
          - '@sylius.resource_controller.view_handler'
          - '@router'
          - '@sylius.repository.payment'

    ph.payum.mollie.factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Sourcefabric\Payum\Mollie\MollieGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: mollie }

    ph.payum.mbe4.factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Sourcefabric\Payum\Mbe4\Mbe4GatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: mbe4 }