PH\Component\Subscription\Model\Subscription:
    properties:
        type:
            - NotBlank:
                groups: [ph]
        amount:
            - GreaterThanOrEqual:
                value: 0.01
                groups: [ph]
            - NotBlank:
                groups: [ph]
            - Type:
                type: integer
                groups: [ph]
        startDate:
            - Date:
                groups: [ph]
        currencyCode:
            - Currency:
                groups: [ph]
