ph_core_homepage:
    path:     /
    defaults: { _controller: PHCoreBundle:Welcome:index }

ph_payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

ph_payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"

ph_core:
    resource: "@PHCoreBundle/Resources/config/routing.yml"
    prefix: /api/v{version}

ph_public_api_core:
    resource: "@PHCoreBundle/Resources/config/routing_public_api.yml"
    prefix: /public-api/v{version}

api_login_check:
    path: /api/v1/login_check
