jms_serializer:
    metadata:
        directories:
            ph-subscription:
                namespace_prefix: "PH\\Component\\Subscription"
                path: "@PHSubscriptionBundle/Resources/config/serializer"
