sylius_resource:
    resources:
        ph.push_destination:
            classes:
                model: PH\Bundle\SubscriptionBundle\Model\PushDestination
                interface: PH\Bundle\SubscriptionBundle\Model\PushDestinationIntefrace
