ph_public_api_core_subscription_create:
    path: /subscriptions/
    methods: [POST]
    defaults:
        _controller: ph.controller.subscription:addAction
        _sylius:
            section: public_api
            form:
                type: PH\Bundle\SubscriptionBundle\Form\Type\SubscriptionType
            serialization_version: $version

ph_public_api_core_payment_method_index:
    path: /payment-methods/
    methods: [GET]
    defaults:
        _controller: sylius.controller.payment_method:indexAction
        _sylius:
            section: public_api
            filterable: true
            criteria:
                supportsRecurring: $supportsRecurring
            serialization_version: $version
            serialization_groups: [Default]

ph_public_api_core_purchase_payment:
    path: /purchase/payment/{token}
    methods: [PUT]
    defaults:
        _controller: ph.controller.subscription:updateAction
        _sylius:
            serialization_version: $version
            form: PH\Bundle\CoreBundle\Form\Type\Purchase\SelectPaymentType
            repository:
                method: getOneByToken
                arguments: [$token]
            state_machine:
                graph: ph_subscription_purchase
                transition: select_payment

ph_public_api_core_purchase_show:
    path: /purchase/{token}
    methods: [GET]
    defaults:
        _controller: ph.controller.subscription:showAction
        repository:
            method: getOneByToken
            arguments: [$token]
        _sylius:
            serialization_version: $version
            serialization_groups: [Detailed]

# payum
ph_public_api_payum_subscription_pay:
    path: /purchase/pay/{token}
    methods: [GET]
    defaults:
        _controller: ph.controller.payum:prepareCaptureAction
        _sylius:
            serialization_version: $version
            redirect:
                route: ph_public_api_payum_subscription_after_pay
                parameters:
                    version: $version

ph_public_api_payum_subscription_after_pay:
    path: /purchase/after-pay/
    methods: [GET, POST]
    defaults:
        _controller: ph.controller.payum:afterCaptureAction
        _sylius:
            serialization_version: $version
