ph_core_homepage:
    path:     /
    defaults: { _controller: PHCoreBundle:Default:index }

ph_core_get_payment_gateways:
    path: /payment-gateways
    methods: [GET]
    defaults:
        _controller: sylius.controller.payment_method:getPaymentGatewaysAction

ph_api_payment_method_create:
    path: /payment-methods/new/{factory}
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.payment_method:createAction
        _sylius:
            section: api
            factory:
                method: createWithGateway
                arguments:
                    gatewayFactory: $factory
            redirect: sylius_api_payment_method_update
            vars:
                route:
                    parameters:
                        factory: $factory

ph_core_payment_method:
    resource: |
        identifier: code
        alias: sylius.payment_method
        section: api
        serialization_version: $version
        criteria:
            code: $code
    type: sylius.resource_api
