ph_public_api_core_subscription_create:
    path: /subscriptions/
    methods: [POST]
    defaults:
        _controller: ph.controller.subscription:addAction
        _sylius:
            section: public_api
            form: PH\Bundle\SubscriptionBundle\Form\Type\SubscriptionType
            serialization_version: $version
            serialization_groups: [Default]
            state_machine:
                graph: ph_subscription_purchase
                transition: select_payment

ph_public_api_core_subscription_show:
    path: /subscriptions/{token}
    methods: [GET]
    defaults:
        _controller: ph.controller.subscription:showAction
        repository:
            method: getOneByToken
            arguments: [$token]
        _sylius:
            serialization_version: $version
            serialization_groups: [Default]

ph_public_api_core_payment_method_index:
    path: /payment-methods/
    methods: [GET]
    defaults:
        _controller: sylius.controller.payment_method:indexAction
        _sylius:
            section: public_api
            filterable: true
            criteria:
                supportsRecurring: $supportsRecurring
            serialization_version: $version
            serialization_groups: [Default]

# payum
ph_public_api_payum_subscription_pay:
    path: /subscriptions/{token}/pay/
    methods: [GET]
    defaults:
        _controller: ph.controller.payum:prepareCaptureAction
        _sylius:
            serialization_version: $version
            redirect:
                route: ph_public_api_payum_subscription_after_pay
                parameters:
                    version: $version
                    redirect: $redirect

ph_public_api_payum_subscription_after_pay:
    path: /subscriptions/after-pay/
    methods: [GET, POST]
    defaults:
        _controller: ph.controller.payum:afterCaptureAction
        _sylius:
            serialization_version: $version
