ph_core_get_payment_gateways:
    path: /payment-gateways/
    methods: [GET]
    defaults:
        _controller: sylius.controller.payment_method:getPaymentGatewaysAction

ph_api_payment_method_create:
    path: /payment-methods/new/{factory}
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.payment_method:createAction
        _sylius:
            section: api
            factory:
                method: createWithGateway
                arguments:
                    gatewayFactory: $factory
            redirect: sylius_api_payment_method_update
            vars:
                route:
                    parameters:
                        factory: $factory

ph_core_payment_method:
    resource: |
        identifier: code
        alias: sylius.payment_method
        section: api
        serialization_version: $version
        only: ["show", "delete", "update"]
        criteria:
            code: $code
    type: sylius.resource_api

ph_core_payment_method_index:
    path: /payment-methods/
    methods: [GET]
    defaults:
        _controller: sylius.controller.payment_method:indexAction
        _sylius:
            section: api
            filterable: true
            criteria:
                supportsRecurring: $supportsRecurring
            serialization_version: $version

ph_api_subscription_payment_complete:
    path: /subscriptions/{subscriptionId}/payments/{id}/complete
    methods: [PUT]
    defaults:
        _controller: sylius.controller.payment:applyStateMachineTransitionAction
        _sylius:
            event: complete
            repository:
                method: findOneBySubscriptionId
                arguments:
                    id: $id
                    subscriptionId: $subscriptionId
            state_machine:
                graph: ph_payment
                transition: complete
            section: api
            return_content: false

ph_payum_payment_cancel:
    path: /subscriptions/{subscriptionId}/payments/{id}/cancel
    methods: [DELETE]
    defaults:
        _controller: ph.controller.payum:cancelAction
        _sylius:
            serialization_version: $version
            redirect:
                route: ph_payum_payment_after_cancel
                parameters:
                    version: $version

ph_payum_payment_after_cancel:
    path: /payments/after-cancel/
    methods: [GET, POST]
    defaults:
        _controller: ph.controller.payum:afterCancelAction
        _sylius:
            serialization_version: $version

# webhook bundle
ph_api_webhooks:
    resource: |
        alias: ph.webhook
        section: api
        serialization_version: $version
    type: sylius.resource_api

ph_api_subscriptions:
    resource: |
        alias: ph.subscription
        section: api
        only: ["index", "show", "delete"]
        serialization_version: $version
    type: sylius.resource_api

ph_api_subscriptions_create:
     path: /subscriptions/
     methods: [POST]
     defaults:
         _controller: ph.controller.subscription:addAction
         _sylius:
             section: api
             serialization_version: $version
