services:
#    ph_core.example:
#        class: PH\Bundle\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    sylius.invoice_number_generator:
        class: Sylius\Component\Core\Payment\IdBasedInvoiceNumberGenerator
