services:
    sylius.invoice_number_generator:
        class: Sylius\Component\Core\Payment\IdBasedInvoiceNumberGenerator

    ph.custom_factory.payment_method:
        class: Sylius\Component\Core\Factory\PaymentMethodFactory
        decorates: sylius.factory.payment_method
        public: false
        arguments:
            - "@ph.custom_factory.payment_method.inner"
            - "@sylius.factory.gateway_config"

    sylius.form.extension.type.payment_method:
        class: PH\Bundle\CoreBundle\Form\Extension\PaymentMethodTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\PaymentBundle\Form\Type\PaymentMethodType }
