services:
    ph.subscription_token_assigner:
        class: PH\Component\Core\Assigner\SubscriptionTokenAssigner
        arguments:
           - "@sylius.random_generator"

    sylius.invoice_number_generator:
        class: Sylius\Component\Core\Payment\IdBasedInvoiceNumberGenerator

    ph.custom_factory.payment_method:
        class: PH\Component\Core\Factory\PaymentMethodFactory
        decorates: sylius.factory.payment_method
        public: false
        arguments:
            - "@ph.custom_factory.payment_method.inner"
            - "@sylius.factory.gateway_config"

    ph.form.extension.type.payment_method:
        class: PH\Bundle\CoreBundle\Form\Extension\PaymentMethodTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\PaymentBundle\Form\Type\PaymentMethodType }

    ph.form.extension.type.subscription:
        class: PH\Bundle\CoreBundle\Form\Extension\SubscriptionTypeExtension
        arguments:
          - '@ph.provider.payment_method'
        tags:
            - { name: form.type_extension, extended_type: PH\Bundle\SubscriptionBundle\Form\Type\SubscriptionType }

    ph.facade.subscription:
        class: PH\Bundle\CoreBundle\Facade\SubscriptionFacade
        arguments:
            - "@ph.factory.subscription_item"
            - "@ph.subscription_processing.subscription_payment_processor.purchase"

    ph.form.type.purchase_select_payment:
        class: PH\Bundle\CoreBundle\Form\Type\Purchase\SelectPaymentType
        arguments:
            - '%ph.model.subscription.class%'
            - ['ph']
        tags:
            - { name: form.type }

    swp.form.type.purchase_payment:
        class: PH\Bundle\CoreBundle\Form\Type\Purchase\PaymentType
        arguments:
            - '%sylius.model.payment.class%'
        tags:
            - { name: form.type }

#subscription processing
    ph.subscription_processing.subscription_payment_processor.purchase:
        class: PH\Component\Core\Processor\SubscriptionPaymentProcessor
        arguments:
            - "@ph.subscription_payment_provider"
            - "new"
####

    ph.payment_method_resolver.default:
        class: Sylius\Component\Payment\Resolver\DefaultPaymentMethodResolver
        arguments:
            - "@sylius.repository.payment_method"

    ph.subscription_payment_provider:
        class: PH\Component\Core\Payment\Provider\SubscriptionPaymentProvider
        arguments:
            - "@ph.payment_method_resolver.default"
            - "@sylius.factory.payment"
            - "@sm.factory"

# resolvers
    ph.state_resolver.subscription_payment:
        class: PH\Component\Core\Resolver\SubscriptionPaymentStateResolver
        arguments:
            - "@sm.factory"

    ph.state_resolver.subscription:
        class: PH\Component\Core\Resolver\SubscriptionStateResolver
        arguments:
            - "@sm.factory"

    ph.payload_sender.subscription:
        class: PH\Bundle\CoreBundle\Sender\SubscriptionPayloadSender
        arguments:
            - "@ph.repository.webhook"
            - "@jms_serializer"

# providers
    ph.provider.payment_method:
        class: PH\Bundle\CoreBundle\Provider\PaymentMethodsProvider
        arguments:
          - '@sylius.repository.payment_method'


    ph.form.extension.type.gateway_configuration.mollie:
        class: PH\Bundle\CoreBundle\Form\Extension\MollieGatewayConfigurationExtensionType
        tags:
            - { name: form.type_extension, extended_type: PH\Bundle\PayumBundle\Form\Type\MollieGatewayConfigurationType }

    ph.form.extension.type.gateway_configuration.mbe4:
        class: PH\Bundle\CoreBundle\Form\Extension\Mbe4GatewayConfigurationExtensionType
        tags:
            - { name: form.type_extension, extended_type: PH\Bundle\PayumBundle\Form\Type\Mbe4GatewayConfigurationType }

    ph.form.extension.type.gateway_configuration.paypal:
        class: PH\Bundle\CoreBundle\Form\Extension\PaypalGatewayConfigurationExtensionType
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\PayumBundle\Form\Type\PaypalGatewayConfigurationType }
