Payum\Core\Model\BankAccount:
    properties:
        holder:
            - NotBlank:
                groups: [ph]
        iban:
            - NotBlank:
                groups: [ph]
            - Iban:
                groups: [ph]
