PH\Component\Core\Model\Subscription:
    constraints:
        - PH\Bundle\CoreBundle\Validator\Constraint\AmountRange:
            groups: [ph]
    properties:
        method:
            - NotBlank:
                groups: [ph]
        intention:
            - NotBlank:
                groups: [ph]
        source:
            - NotBlank:
                groups: [ph]
