imports:
    - { resource: "@PHCoreBundle/Resources/config/app/state_machine/ph_subscription.yml" }
    - { resource: "@PHCoreBundle/Resources/config/app/state_machine/ph_subscription_purchase.yml" }
    - { resource: "@PHCoreBundle/Resources/config/app/state_machine/ph_subscription_payment.yml" }
    - { resource: "@PHCoreBundle/Resources/config/app/state_machine/ph_payment.yml" }
