source 'https://rubygems.org'

# Middleman
gem 'middleman', :git => "git@github.com:middleman/middleman.git", :branch => "master"
gem 'middleman-syntax', '~> 3.0.0'
gem 'middleman-autoprefixer', '~> 2.7.0'
gem "middleman-sprockets", "~> 4.1.0"
gem 'rouge', '~> 2.0.5'
gem 'redcarpet', '~> 3.4.0'
gem 'opal'
