winzou_state_machine:
    sylius_order_checkout:
        class: PH\Component\Core\Model\Order #"%sylius.model.order.class%"
        property_path: checkoutState
        graph: sylius_order_checkout
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            payment_skipped: ~
            payment_selected: ~
            completed: ~
        transitions:
            skip_payment:
                from: [cart, payment_selected]
                to: payment_skipped
            select_payment:
                from: [cart, payment_selected, payment_skipped]
                to: payment_selected
            complete:
                from: [payment_selected, payment_skipped]
                to: completed
        callbacks:
            after:
                ph_process_cart:
                    on: ["select_payment", "skip_payment"]
                    do: ["@sylius.order_processing.order_processor", "process"]
                    args: ["object"]
                ph_create_order:
                    on: ["complete"]
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object", "event", "'create'", "'sylius_order'"]
                ph_save_checkout_completion_date:
                    on: ["complete"]
                    do: ["object", "completeCheckout"]
                    args: ["object"]
#                sylius_skip_shipping:
#                    on: ["address"]
#                    do: ["@sylius.state_resolver.order_checkout", "resolve"]
#                    args: ["object"]
#                    priority: 1
#                sylius_skip_payment:
#                    on: ["select_shipping"]
#                    do: ["@sylius.state_resolver.order_checkout", "resolve"]
#                    args: ["object"]
#                    priority: 1
