winzou_state_machine:
    ph_order:
        class: "%sylius.model.order.class%"
        property_path: state
        graph: ph_order
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            new: ~
            cancelled: ~
            fulfilled: ~
        transitions:
            create:
                from: [cart]
                to: new
            cancel:
                from: [new]
                to: cancelled
            fulfill:
                from: [new]
                to: fulfilled
        callbacks:
            before:
                ph_assign_number:
                    on: ["create"]
                    do: ["@sylius.order_number_assigner", "assignNumber"]
                    args: ["object"]
                ph_assign_token:
                    on: ["create"]
                    do: ["@ph.order_token_assigner", "assignTokenValue"]
                    args: ["object"]
            after:
                ph_request_payment:
                    on: ["create"]
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object", "event", "'request_payment'", "'ph_order_payment'"]
                ph_create_payment:
                    on: ["create"]
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object.getPayments()", "event", "'create'", "'ph_payment'"]
                ph_cancel_payment:
                    on: ["cancel"]
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object.getPayments()", "event", "'cancel'", "'ph_payment'"]
                ph_cancel_order_payment:
                    on: ["cancel"]
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object", "event", "'cancel'", "'ph_order_payment'"]
                ph_cancel_order:
                    on: ["cancel"]
                    do: ["@sylius.inventory.order_inventory_operator", "cancel"]
                    args: ["object"]
