winzou_state_machine:
    ph_order_payment:
        class: "%sylius.model.order.class%"
        property_path: paymentState
        graph: ph_order_payment
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            awaiting_payment: ~
            partially_paid: ~
            cancelled: ~
            paid: ~
            partially_refunded: ~
            refunded: ~
        transitions:
            request_payment:
                from: [cart]
                to: awaiting_payment
            partially_pay:
                from: [awaiting_payment, partially_paid]
                to: partially_paid
            cancel:
                from: [awaiting_payment]
                to: cancelled
            pay:
                from: [awaiting_payment, partially_paid]
                to: paid
            partially_refund:
                from: [paid, partially_paid, partially_refunded]
                to: partially_refunded
            refund:
                from: [paid, partially_paid, partially_refunded]
                to: refunded
        callbacks:
            after:
                ph_resolve_state:
                    on: ["pay"]
                    do: ["@ph.state_resolver.order", "resolve"]
                    args: ["object"]
