winzou_state_machine:
    ph_payment:
        class: "%sylius.model.payment.class%"
        property_path: state
        graph: ph_payment
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            new: ~
            processing: ~
            completed: ~
            failed: ~
            cancelled: ~
            refunded: ~
        transitions:
            create:
                from: [cart]
                to: new
            process:
                from: [new]
                to: processing
            complete:
                from: [new, processing]
                to: completed
            fail:
                from: [new, processing]
                to: failed
            cancel:
                from: [new, processing]
                to: cancelled
            refund:
                from: [completed]
                to: refunded
        callbacks:
            after:
                ph_process_order:
                    on: ["fail", "cancel"]
                    do: ["@ph.order_processing.order_payment_processor.after_checkout", "process"]
                    args: ["object.getOrder()"]
                ph_resolve_state:
                    on: ["complete", "refund"]
                    do: ["@ph.state_resolver.order_payment", "resolve"]
                    args: ["object.getOrder()"]
