winzou_state_machine:
    ph_payment:
        class: "%sylius.model.payment.class%"
        property_path: state
        graph: ph_payment
        state_machine_class: "%sylius.state_machine.class%"
        states:
            new: ~
            processing: ~
            completed: ~
            failed: ~
            cancelled: ~
            refunded: ~
            authorized: ~
        transitions:
            process:
                from: [new]
                to: processing
            authorize:
                from: [new]
                to: authorized
            complete:
                from: [new, processing, authorized]
                to: completed
            fail:
                from: [new, processing, authorized]
                to: failed
            cancel:
                from: [new, processing, authorized]
                to: cancelled
            refund:
                from: [completed]
                to: refunded
        callbacks:
            after:
                ph_process_subscription:
                    on: ["fail", "cancel"]
                    do: ["@ph.state_resolver.subscription_payment", "resolve"]
                    args: ["object.getSubscription()"]
                ph_cancel_payment:
                    on: ["cancel"]
                    do: ["object", "cancel"]
                    args: ["object"]
                ph_resolve_state:
                    on: ["complete", "refund"]
                    do: ["@ph.state_resolver.subscription_payment", "resolve"]
                    args: ["object.getSubscription()"]
                ph_send_payload:
                    on: ["authorize"]
                    do: ["@ph.payload_sender.subscription", "send"]
                    args: ["object.getSubscription()"]
